# Generated by Django 4.1.1 on 2022-09-22 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Platera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('izena', models.CharField(max_length=50)),
                ('ingredienteak', models.TextField()),
                ('alergenoak', models.TextField()),
                ('prezioa', models.FloatField()),
            ],
        ),
    ]
