# Generated by Django 3.1.4 on 2022-10-11 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platerak', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Erosketa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('erabiltzailea', models.CharField(max_length=50)),
                ('plateraIzena', models.TextField()),
                ('komentarioak', models.TextField()),
                ('kantitatea', models.IntegerField()),
                ('totala', models.FloatField()),
            ],
        ),
        migrations.AlterField(
            model_name='platera',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
